version: "3.4"
services:

  op-geth:
    image: us-docker.pkg.dev/oplabs-tools-artifacts/images/op-geth:v1.101308.2
    restart: unless-stopped
    stop_grace_period: 5m
    entrypoint: geth
    env_file:
      - ./envs/${NETWORK_NAME}/op-geth.env
      - .env
    volumes:
      - ./secrets/:/secrets
      - /mnt/disks/op-geth/:/geth
    ports:
      - ${GETH_AUTHRPC_PORT:-8551}:8551
      - ${GETH_HTTP_PORT:-8545}:8545
      - ${GETH_WS_PORT:-854}:8546
      - ${GETH_DISCOVERY_PORT:-30303}:${GETH_DISCOVERY_PORT:-30303}/udp
      - ${GETH_PORT:-30304}:${GETH_PORT:-30304}/tcp
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  # dtl:
  # geth:
  # prometheus_data:
  # grafana_data:
  # influxdb_data:
  op_geth:
  # torrent_downloads:
